@startuml flow.puml
title Payment Service Flow (Happy Path)


(Begin) --> (payment_initiated) : initiate_payment
(payment_initiated) --> (amount_blocked) : block_amount
(amount_blocked) --> (fraud_check_pending) : send_fraud_check

(fraud_check_pending) --> (fraud_check_success) : fraud_success
(fraud_check_success) --> (payment_executed) : execute_payment
(payment_executed) --> (success_notified) : notify_success

(fraud_check_pending) --> (fraud_check_manual) : fraud_send_manual
(fraud_check_manual) -> (fraud_check_success) : fraud_manual_approved
(fraud_check_manual) -left-> (fraud_check_failed) : fraud_manual_rejected

(fraud_check_pending) --> (fraud_check_failed) : fraud_detected
(fraud_check_failed) --> (amount_released) : release_amount
(amount_released) --> (failure_notified) : notify_failure


@enduml
